### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by BriefGuo** [jbalboni/atom-language-aspx#3]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\gyj04\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:550:9)
<unknown> (C:\Users\gyj04\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:172:43)
```

**Comment by jbalboni** [comment]
I will look at this soon.

**Comment by willl** [comment]
All you need to do is rename the scoped-properties to settings and it should work fine.

**Comment by jbalboni** [comment]
This is updated now.

**Comment by BriefGuo** [comment]
It's today that I have seen. Thank you.

Date: Wed, 15 Apr 2015 14:39:54 -0700
